package com.mordva.sqlite.model

data class MovieLocalDto(
    val id: Int = -1,
    val type: String? = null,
    val name: String? = null,
    val rating: RatingLocalDto? = null,
    val description: String? = null,
    val votes: VotesLocalDto? = null,
    val distributors: DistributorsLocalDto? = null,
    val premiere: PremiereLocalDto? = null,
    val slogan: String? = null,
    val year: Int? = null,
    val budget: BudgetLocalDto? = null,
    val poster: PosterLocalDto? = null,
    val facts: List<FactLocalDto> = listOf(),
    val genres: List<ItemNameLocalDto> = listOf(),
    val countries: List<ItemNameLocalDto> = listOf(),
    val persons: List<PersonMovieLocalDto> = listOf(),
    val watchability: WatchabilityLocalDto = WatchabilityLocalDto(listOf()),
    val alternativeName: String? = null,
    val backdrop: PosterLocalDto? = null,
    val movieLength: Int? = null,
    val status: String? = null,
    val ageRating: Int? = null,
    val ratingMpaa: String? = null,
    val updatedAt: String? = null,
    val shortDescription: String? = null,
    val similarMovies: List<MovieLocalDto> = listOf(),
    val sequelsAndPrequels: List<MovieLocalDto> = listOf(),
    val logo: PosterLocalDto? = null,
    val top10: Int? = null,
    val top250: Int? = null,
    val audience: List<AudienceLocalDto> = listOf(),
    val isSeries: Boolean? = null,
    val seriesLength: Int? = null,
    val totalSeriesLength: Int? = null,
    val releaseYears: List<ReleaseYearsLocalDto> = listOf(),
    val seasonsInfo: List<SeasonLocalDto>? = null,
    val lists: List<String> = listOf()
)